# Generated by Django 4.2.11 on 2024-03-19 05:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_image_detect", "0004_alter_emailcruddata_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcruddata",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="title", unique=True
            ),
        ),
    ]
